#!/bin/bash
source ~/repos/dotfiles/aliases
source ~/repos/dotfiles/funcs
source ~/repos/dotfiles/osx-git-completion.bash
echo "> source osx_bashrc"

alias ls="ls -G"
alias showhidden="defaults write com.apple.finder AppleShowAllFiles YES"
alias hidefiles="defaults write com.apple.finder AppleShowAllFiles NO"
alias sslchrome="SSLKEYLOGFILE=~/keylogfile.log /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

export ANDROID_HOME=~/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PATH=$HOME/Library/Haskell/bin:$PATH
export PATH=$PATH:/Users/y/Library/Python/3.7/bin
export HISTFILESIZE=10000
export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH

export PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\] \[\e[0;31m\]$(parse_git_branch)\[\e[0m\]\n\$ '
